# Controls global settings, Can be overridden in individual scrape configs
global:
  scrape_interval: 15s
  # How often to evaluate rules
  evaluation_interval: 30s

#  Controls how often Prometheus will scrape targets
scrape_configs:
  - job_name: prometheus
    static_configs:
    # A list of targets to scrape (HTTP endpoints exposing Prometheus metrics)
      - targets: ['prometheus:9090']

  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']
      
  - job_name: apps
    static_configs:
      - targets: ['host.docker.internal:8003','host.docker.internal:8004','host.docker.internal:8006','host.docker.internal:8007','host.docker.internal:8008','host.docker.internal:8009']

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'apps'
    static_configs:
      - targets:
          - host.docker.internal:8011   # strategy_runner
          - host.docker.internal:8015
          - host.docker.internal:8016   # gateway_oms_exporter (earlier)
          - host.docker.internal:8017   # oms_lifecycle_exporter (earlier)
          - host.docker.internal:8018   # risk_drawdown_exporter (NEW)
          - host.docker.internal:8019   # pairs_exporter
          - host.docker.internal:8021   # broker_reconciler.py
          - host.docker.internal:8017   # zerodha_gateway
          - host.docker.internal:8022   # budget_source exporter
          - host.docker.internal:8023   # order_budget_guard
          - host.docker.internal:8024   # accounting_pnl
          - host.docker.internal:8025   # oms exporter