symbols:
  from_tokens_csv: configs/tokens.csv      # uses rows where subscribe==1
# Which symbols to backtest
# symbols:
#   list: [RELIANCE, TCS, SBIN, HDFCBANK]

# Timeframes (minutes)
timeframes_min: [1, 3, 5, 15]
# timeframes_min: [3, 5]

# Parallelism
processes: auto

# Data window
days_lookback: 120

# Capital per stock used by the backtester (backtest-only, not live sizing)
per_stock_capital: 50000
allow_short: True

# Simple transaction costs
costs:
  slippage_bps: 5         # 0.05%
  flat_per_side: 0.0
  pct_taxes: 0.0005       # 5 bps

# Strategies with per-timeframe parameter grids (falls back to 'params' if 'params_by_tf' absent)
strategies:
  - name: EMA_CROSS
    module: strategy.strategies.ema_cross
    class: EMACross
    params_by_tf:
      "1":  { fast: [5,8,12],     slow: [20,50,100] }
      "3":  { fast: [8,12],       slow: [30,50,100] }
      "5":  { fast: [10,12,15],   slow: [30,50,100,200] }
      "15": { fast: [12,20],      slow: [50,100,200] }
    constraints: "fast < slow"

  - name: MACD_SIGNAL
    module: strategy.strategies.macd_signal
    class: MACDSignal
    params_by_tf:
      "1":  { fast: [12], slow: [26], signal: [9] }
      "3":  { fast: [12], slow: [26], signal: [9] }
      "5":  { fast: [12], slow: [26], signal: [9] }
      "15": { fast: [12], slow: [26], signal: [9] }

  - name: MOMENTUM_ROC
    module: strategy.strategies.momentum_roc
    class: MomentumROC
    params_by_tf:
      "1":  { lookback: [10,12,14], band: [0.0, 0.2] }
      "3":  { lookback: [10,12,14], band: [0.0, 0.2] }
      "5":  { lookback: [12,14],    band: [0.0, 0.2] }
      "15": { lookback: [14,20],    band: [0.0, 0.3] }

  - name: BB_BREAKOUT
    module: strategy.strategies.bollinger_breakout
    class: BollingerBreakout
    params_by_tf:
      "1":  { period: [20], k: [2.0] }
      "3":  { period: [20], k: [2.0] }
      "5":  { period: [20], k: [2.0] }
      "15": { period: [20], k: [2.0] }

  - name: BB_REVERSION
    module: strategy.strategies.bollinger_reversion
    class: BollingerReversion
    params_by_tf:
      "1":  { period: [20], k: [2.0] }
      "3":  { period: [20], k: [2.0] }
      "5":  { period: [20], k: [2.0] }
      "15": { period: [20], k: [2.0] }

  - name: DONCHIAN_BREAK
    module: strategy.strategies.donchian_breakout
    class: DonchianBreakout
    params_by_tf:
      "1":  { lookback: [20] }
      "3":  { lookback: [20] }
      "5":  { lookback: [20] }
      "15": { lookback: [20, 55] }

  - name: KELTNER_BREAK
    module: strategy.strategies.keltner_breakout
    class: KeltnerBreakout
    params_by_tf:
      "1":  { ema_period: [20], atr_period: [14], mult: [2.0] }
      "3":  { ema_period: [20], atr_period: [14], mult: [2.0] }
      "5":  { ema_period: [20], atr_period: [14], mult: [2.0] }
      "15": { ema_period: [20], atr_period: [14], mult: [2.0, 2.5] }

  - name: SUPERTREND
    module: strategy.strategies.supertrend_trend
    class: SupertrendTrend
    params_by_tf:
      "1":  { atr_period: [10], mult: [3.0] }
      "3":  { atr_period: [10], mult: [3.0] }
      "5":  { atr_period: [10], mult: [3.0] }
      "15": { atr_period: [10,14], mult: [2.5, 3.0] }

  - name: HEIKIN_TREND
    module: strategy.strategies.heikin_trend
    class: HeikinTrend
    params_by_tf:
      "1":  { }
      "3":  { }
      "5":  { }
      "15": { }

  - name: CCI_REV
    module: strategy.strategies.cci_reversion
    class: CCIReversion
    params_by_tf:
      "1":  { period: [20], th_hi: [100], th_lo: [-100] }
      "3":  { period: [20], th_hi: [100], th_lo: [-100] }
      "5":  { period: [20], th_hi: [100], th_lo: [-100] }
      "15": { period: [20], th_hi: [100, 150], th_lo: [-100, -150] }

  - name: ZSCORE_REV
    module: strategy.strategies.meanreversion_zscore
    class: MeanReversionZScore
    params_by_tf:
      "1":  { period: [20], z_entry: [1.5, 2.0] }
      "3":  { period: [20], z_entry: [1.5, 2.0] }
      "5":  { period: [20], z_entry: [1.5, 2.0] }
      "15": { period: [20], z_entry: [1.5, 2.5] }

  - name: VWAP_REV
    module: strategy.strategies.vwap_reversion
    class: VWAPReversion
    params_by_tf:
      "1":  { z: [1.0, 1.5] }
      "3":  { z: [1.0, 1.5] }
      "5":  { z: [1.0, 1.5] }
      "15": { z: [1.0, 1.5] }

  - name: ENSEMBLE_KOFN
    module: strategy.strategies.ensemble_kofn
    class: EnsembleKofN
    params_by_tf:
      "1":  { k: [3], rsi_lb: [30], rsi_ub: [70], ema_period: [20], roc_lb: [12] }
      "3":  { k: [3], rsi_lb: [30], rsi_ub: [70], ema_period: [20], roc_lb: [12] }
      "5":  { k: [3], rsi_lb: [30], rsi_ub: [70], ema_period: [20], roc_lb: [12] }
      "15": { k: [3], rsi_lb: [30], rsi_ub: [70], ema_period: [20], roc_lb: [12] }

  # - name: ML_SIGNAL
  #   module: strategy.strategies.ml_signal
  #   class: MLSignal
  #   params_by_tf:
  #     "1":  { model_name: ["baseline"] }
  #     "3":  { model_name: ["baseline"] }
  #     "5":  { model_name: ["baseline"] }
  #     "15": { model_name: ["baseline"] }
